name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  migrate:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            shell: pwsh
            build_script: build.ps1
            migrate_bin: build_x64/bin/Release/sources-migrate.exe

          - os: ubuntu-latest
            shell: bash
            build_script: build.sh
            migrate_bin: build_linux/bin/sources-migrate

          - os: macos-latest
            shell: bash
            build_script: build.sh
            migrate_bin: build/bin/sources-migrate

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Clone Axmol
        shell: ${{ matrix.shell }}
        run: |
          git clone --depth=1 https://github.com/axmolengine/axmol "$RUNNER_TEMP/axmol"

      - name: Build sources-migrate (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          & "$env:RUNNER_TEMP\axmol\build.ps1" `
            -d "$env:RUNNER_TEMP\axmol" `
            -xb '--config','Release','--target','sources-migrate'

      - name: Build sources-migrate (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          chmod +x "$RUNNER_TEMP/axmol/build.sh"
          "$RUNNER_TEMP/axmol/build.sh" \
            -d "$RUNNER_TEMP/axmol" \
            -xb --config Release --target sources-migrate

      - name: Migrate sources (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git checkout main
          & "$env:RUNNER_TEMP\axmol\build_x64\bin\Release\sources-migrate.exe" `
            "$PWD" --fuzzy

          Copy-Item "$env:RUNNER_TEMP\axmol\build.ps1" "./build.ps1" -Force
          git add build.ps1 -f

      - name: Migrate sources (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          git checkout main

          "$RUNNER_TEMP/axmol/${{ matrix.migrate_bin }}" \
            "$PWD" --fuzzy

          cp "$RUNNER_TEMP/axmol/build.sh" ./build.sh
          git add build.sh -f

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Migrate to compile with latest Axmol
          branch: migrate-to-axmol-latest
          create_branch: true
          push_options: --force